gpus: [0, 1, 3]

outDir: "comp_det"
train:
    lr: 5e-5
    local_rank: 0
    save_best_acc: True
    is_distributed: True
    eval_ep: 10
    batch_size: 16
    load_all_pretrained: False
    train_module: "lib.train.comp_det_trainer"
    train_path: "lib/train/comp_det_trainer.py"

train_dataset:
    # rootDir: '../../dataset/graph_dataset_rererefine_copy'
    module: 'lib.datasets.light_stage.rico_graph_dataset'
    path: 'lib/datasets/light_stage/rico_graph_dataset.py'
    rootDir: '../../dataset/rico_graph_discard_rarelabels'
    index_json: 'index_train_new.json'
    bg_color_mode: 'bg_color_orig'

test_dataset:
    module: 'lib.datasets.light_stage.rico_graph_dataset'
    path: 'lib/datasets/light_stage/rico_graph_dataset.py'
    rootDir: '../../dataset/rico_graph_discard_rarelabels'
    index_json: 'index_test_new.json'
    bg_color_mode: 'bg_color_orig'

test:
    vis_bbox: False
    val_nms: False
    eval_merge: False

network:

    network_module: 'lib.networks.comp_det_net'
    network_path: 'lib/networks/comp_det_net.py'
    loc_type: 'regress_absolute_box'
    remove_pos: False
    remove_type: False
    remove_img: False
    remove_gnn: True

    confidence_weight: 5.0
    use_attn_weight: False
    #bbox_regression_type: 'step_voting'
    bbox_vote_radius: 0.001
    #bbox_regression_type: 'center_regress'
    #bbox_regression_type:  'anchor_params'
    bbox_regression_type:  'absolute'
    
    #bbox_regression_type: anchor_encoding
    #bbox_regression_type:  'direct'
    #bbox_regression_type: 'attn_average'
    center_reg_loss:
        weight: 5.0
    pos_embedder:
        multires: 9
        out_dim: 128
        
    type_embedder:
        out_dim: 128
        class_num: 11

    img_embedder:
        out_dim: 128
        name: 'resnet50'
        type: 'resnet50'
        roi_feat_way: 'FPN'

    reg_loss:
        type: 'ciou_loss'
        weight: 10
    
    cls_loss:
        type: 'cross_entropy_loss'
        weight: 1

    gnn_fn:
      gnn_type: 'GPSModel'
      latent_dims: [128, 128, 128, 128, 128, 128, 128, 128, 128]
      num_heads: [4, 4, 4, 4, 4, 4, 4, 4, 4] 
      out_dim: 128
      local_gnn_type: 'GINEConv'
      global_model_type: 'Transformer'
      act_fn: 'relu'
      dropout: 0.0
      attn_dropout: 0.2
      layer_norm: True
      batch_norm: False
    
    cls_fn:
        classes: 24

    loc_fn: 
      clip_val: True
      classes: 4
      loc_type: 'classifier_two_branches'    
      gnn_latent_dims: [128, 128, 128]
      num_heads: [4, 4, 4] 
      out_dim: 128
      local_gnn_type: 'GINConv'
      global_model_type: 'Transformer'
      act_fn: 'relu'
      dropout: 0.0
      attn_dropout: 0.2
      layer_norm: True
      batch_norm: False
  
visualizer:
      img_folder: '/media/sda2/ljz_dataset/combined'