gpus: [0, 1, 2, 3]

train:
    lr: 1e-5
    local_rank: 3
    save_best_acc: True
    is_distributed: False
    eval_ep: 10
    batch_size: 6

train_dataset:
    index_json: 'index_tmp.json'

test_dataset:
    index_json: 'index_tmp.json'

test:
    vis_bbox: True
    val_nms: False

network:
    network_module: 'lib.networks.network'
    network_path: 'lib/networks/network_new.py'
    use_attn_weight: False
    #bbox_regression_type: 'step_voting'
    bbox_vote_radius: 0.001
    #bbox_regression_type: 'center_regress'
    bbox_regression_type: 'attn_average'
    #bbox_regression_type:  'offset_based_on_layer'
    pos_embedder:
        multires: 9
        out_dim: 128
        
    type_embedder:
        out_dim: 128
        class_num: 11

    img_embedder:
        out_dim: 128
        name: 'resnet50'

    reg_loss:
        weight: 1

    gnn_fn:
      gnn_type: 'GPSModel'
      latent_dims: [128, 128, 128, 128, 128, 128, 128, 128, 128]
      num_heads: [4, 4, 4, 4, 4, 4, 4, 4, 4] 
      out_dim: 128
      local_gnn_type: 'GINConv'
      global_model_type: 'Transformer'
      act_fn: 'relu'
      dropout: 0.0
      attn_dropout: 0.2
      layer_norm: True
      batch_norm: False
    loc_fn: 
      loc_type: 'classifier'
      gnn_latent_dims: [128, 128, 128]
      num_heads: [4, 4, 4] 
      out_dim: 128
      local_gnn_type: 'GINConv'
      global_model_type: 'Transformer'
      act_fn: 'relu'
      dropout: 0.0
      attn_dropout: 0.2
      layer_norm: True
      batch_norm: False
      
    center_reg_loss:
      weight: 1.0