gpus: [0, 1, 2, 3]

train:
    lr: 5e-5
    local_rank: 0
    save_best_acc: True
    is_distributed: True
    eval_ep: 10
    batch_size: 4

train_dataset:
    #rootDir: '../../dataset/graph_dataset_rerefine_large_graph_fill_blank'
    rootDir: '../../dataset/graph_dataset_rerefine'
    index_json: 'index_train.json'

test_dataset:
    #rootDir: '../../dataset/graph_dataset_rerefine_large_graph_fill_blank'
    rootDir: '../../dataset/graph_dataset_rerefine'
    index_json: 'index_test.json'

test:
    vis_bbox: False
    val_nms: False

network:
    confidence_weight: 5.0
    use_attn_weight: False
    #bbox_regression_type: 'step_voting'
    bbox_vote_radius: 0.001
    #bbox_regression_type: 'center_regress'
    bbox_regression_type:  'offset_based_on_layer'
    #bbox_regression_type: 'attn_average'
    pos_embedder:
        multires: 9
        out_dim: 128
        
    type_embedder:
        out_dim: 128
        class_num: 11

    img_embedder:
        out_dim: 128
        name: 'resnet50'

    center_reg_loss:
        weight: 5.0

    reg_loss:
        weight: 10

    cls_loss:
        weight: 1
        
    gnn_fn:
      gnn_type: 'GPSModel_with_voting'
      latent_dims: [128, 128, 128, 128, 128, 128, 128, 128, 128]
      num_heads: [4, 4, 4, 4, 4, 4, 4, 4, 4] 
      out_dim: 128
      local_gnn_type: 'GINEConv'
      global_model_type: 'MultheadAttention_with_bias'
      act_fn: 'relu'
      dropout: 0.0
      attn_dropout: 0.2
      layer_norm: True
      batch_norm: False
    loc_fn: 
      classes: 5
      loc_type: 'classifier_with_confidence'
      gnn_latent_dims: [128, 128, 128]
      num_heads: [4, 4, 4] 
      out_dim: 128
      local_gnn_type: 'GINConv'
      global_model_type: 'Transformer'
      act_fn: 'relu'
      dropout: 0.0
      attn_dropout: 0.2
      layer_norm: True
      batch_norm: False