train:
    lr: 5e-5
    local_rank: 1
    save_best_acc: False
  
test:
    vis_bbox: False
    val_nms: True

train_dataset:
    rootDir: '../../dataset/graph_dataset_rerefine'
    index_json:  = 'index_correct.json'

test_dataset:
    rootDir: '../../dataset/graph_dataset_rerefine'
    index_json: 'index_correct.json'

network:
    pos_embedder:
        multires: 9
        out_dim: 128
        
    type_embedder:
        out_dim: 128
        class_num: 11

    img_embedder:
        outdim: 128
        name: 'resnet50'

    gnn_fn:
      gnn_type: 'GPSModel'
      latent_dims: [128, 128, 128, 128, 128, 128, 128, 128, 128]
      num_heads: [4, 4, 4, 4, 4, 4, 4, 4, 4] 
      out_dim: 128
      local_gnn_type: 'GINConv'
      global_model_type: 'Transformer'
      act_fn: 'relu'
      dropout: 0.0
      attn_dropout: 0.2
      layer_norm: True
      batch_norm: False